name: sm_cli
description: A Flutter Clean Architecture CLI generator for scalable production apps (Riverpod,Bloc, Getx, Provider API, routing, themes, feature-based structure).
version: 1.0.0

homepage: https://github.com/flutterbysunny/sm_cli
repository: https://github.com/flutterbysunny/sm_cli

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.9.0
  args: ^2.7.0
  mason: ^0.1.0-dev.57
  io: ^1.0.5
  interact: ^2.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6